# Generated by Django 2.1.4 on 2019-01-07 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watsons', '0006_location_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pocket_other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_other', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watsons.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watsons.Product')),
            ],
        ),
    ]
