# Generated by Django 2.1.5 on 2019-01-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watsons', '0007_pocket_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num', models.IntegerField(default=0)),
                ('Date', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='pocket_other',
            old_name='total_other',
            new_name='total_Care',
        ),
        migrations.RemoveField(
            model_name='pocket_other',
            name='product',
        ),
        migrations.AddField(
            model_name='pocket_other',
            name='total_Cosmetic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pocket_other',
            name='total_Snacks',
            field=models.IntegerField(default=0),
        ),
    ]
